name: green_genie
description: "Your personal carbon emission calculator"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # riverpod
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # retrofit
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # needed by both riverpod and retrofit
  build_runner: ^2.4.15

  # riverpod
  riverpod_generator: ^2.6.4
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4

  # retrofit
  retrofit_generator: ^9.1.9
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - .env